{% set version = "1.4.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggvenndiagram
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggVennDiagram_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggVennDiagram/ggVennDiagram_{{ version }}.tar.gz
  sha256: 50f00881bfe34a6fde4d828db27aa76db432ab071eb2d363c0c1477667bec4d9

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-aplot
    - r-dplyr
    - r-forcats
    - r-ggplot2 >=3.4.0
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-aplot
    - r-dplyr
    - r-forcats
    - r-ggplot2 >=3.4.0
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('ggVennDiagram')"           # [not win]
    - "\"%R%\" -e \"library('ggVennDiagram')\""  # [win]

about:
  home: https://github.com/gaospecial/ggVennDiagram
  license: GPL-3.0-only
  summary: 'Easy-to-use functions to generate 2-7 sets Venn plot in publication quality. ''ggVennDiagram'' plot Venn using well-defined geometry dataset and ''ggplot2''. The shapes of 2-4 sets Venn use circles and ellipses, while the shapes of 4-7 sets Venn use irregular polygons (4 has both forms), which are developed and
    imported from another package ''venn'', authored by Adrian Dusa. We provided internal functions to integrate shape data with user provided sets data, and calculated the geometry of every regions/intersections of them, then separately plot Venn in three components: set edges, set labels, and regions. From version 1.0,
    it is possible to customize these components as you demand in ordinary ''ggplot2'' grammar.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler
